### ISSUE TITLE
process.stdin.setRawMode(true);

### ISSUE THREAD

**Issue by ch3njust1n** [substack/terminal-menu#25]
I received this error from running the example found on npm. I am using node v0.10.35.

/node_modules/terminal-menu/index.js:62
    process.stdin.setRawMode(true);
TypeError: Object #<Socket> has no method 'setRawMode'
    at new Menu(/terminal-menu/index.js:62:19)
 at module.exports (node_modules/terminal-menu/index.js:9:12)
 at Object.<anonymous> (test.js:3:45)
 at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by Zjaaspoer** [comment]
Yeah, unfortunately I have the exact same problem

**Comment by zarathustrus** [comment]
me too

**Comment by leftstick** [comment]
Possible to upgrade your `node`? I mean the exception is clear, `setRawMode ` doesn't exist on `process.stdin`. The only way is using the newer version of `node`

**Comment by Zjaaspoer** [comment]
Yep, that solved it for me!
