### ISSUE TITLE
"TypeError: Cannot read property 'setRawMode' of null" occurs while using `inquirer`

### ISSUE THREAD

**Issue by leftstick** [substack/terminal-menu#29]
I'd like to collect some user inputs after user selected one item as following:

```javascript
menu.on('select', function(label, index) {
    menu.y = 0;
    menu.reset();
    menu.close();

    inquirer.prompt([{
            type: 'input',
            name: 'name',
            message: 'your name',
            validate: function(pass) {
                return !!pass;
            }
        }], function(res) {
                logger.info('Your name is:', res.name);
                cons();
        });
});
```

But i got errors:

```bash
TypeError: Cannot read property 'setRawMode' of null
    at ReadStream.setRawMode (tty.js:67:15)
    at Interface._setRawMode (readline.js:177:23)
    at Interface.close (readline.js:286:10)
    at PromptUI.UI.close (/Users/haozuo/codes/github/task-runner/node_modules/inquirer/lib/ui/baseUI.js:67:11)
    at PromptUI.UI.onForceClose (/Users/haozuo/codes/github/task-runner/node_modules/inquirer/lib/ui/baseUI.js:45:8)
    at process.emit (events.js:107:17)
```

Since `menu.close();` triggers the `this._input.end();` which caused this error.

I am wondering if it is possible to support user input?

**Comment by derhuerst** [comment]
I get the same error showing two [cli-autocomplete](https://github.com/derhuers/cli-autocomplete) prompts successively. Any news on this?

**Comment by xanisu** [comment]
same error here, trying to build another submenu after first one.
